### ISSUE TITLE
无法将数据库的注入类型改为PostgreSql的DbContext

### ISSUE THREAD

**Issue by light499960904** [i66soft/osharp#274]
### 描述一下BUG
无法将数据库的注入类型改为PostgreSql的DbContext

### 期望行为
在注入数据库服务时，能够注入PostgreSql的Context类型

### 附加上下文，如截图
![image](https://user-images.githubusercontent.com/27767203/156685400-732c22fd-29da-41da-9675-2364992f19a4.png)

**Comment by lianglj** [comment]
您好，邮件已收到
