### ISSUE TITLE
用户登录提示用户声明异常

### ISSUE THREAD

**Issue by hxjhaker** [i66soft/osharp#280]
### 描述一下BUG
调用登录API时，
执行这一步操作
await SignInManager.SignInAsync(user, dto.Remember);

### 附加上下文，如截图
![图片](https://user-images.githubusercontent.com/6397193/162174525-c914558c-9987-4d5c-93d0-a4ec88890d21.png)

### 运行环境
数据库：MySql5.7
初始化数据后，UserClaim  表内容为空，创建新用户后也是为空

**Comment by lianglj** [comment]
您好，邮件已收到
