### ISSUE TITLE
OSharp可以替换DefaultDbContext为自定义DbContext吗

### ISSUE THREAD

**Issue by xuejmnet** [i66soft/osharp#284]
## 您的功能请求与现有问题有关吗？请描述
OSharp可以替换DefaultDbContext为自定义DbContext吗？我这边修改了自定义appsetting下的类，新建了自定义dbcontext继承dbcontextbase，然后初始化后续还是有提示未注册DefaultDbContext

## 描述您想要的需求方案
希望能够替换

## 描述你考虑过的解决方案
希望能够替换

## 附加上下文，比如截图
配置文件
<img width="790" alt="image" src="https://user-images.githubusercontent.com/18061232/173222594-6ac39ec7-25be-4b8a-afc2-ab683e1dcd21.png">
数据库上下文
<img width="982" alt="image" src="https://user-images.githubusercontent.com/18061232/173222621-8fa37739-dfc7-4e17-8fb0-594406fd3c31.png">
启动
<img width="822" alt="image" src="https://user-images.githubusercontent.com/18061232/173222633-8d0958ed-d3cd-471f-aae7-70f4c2f4bd44.png">

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/18061232/173222570-8ae1c8c0-97cf-4ef3-b63d-9a2f3877ca74.png">

**Comment by gmf520** [comment]
https://github.com/gmf520/osharp-ns20-samples/tree/master/src/OSharp.Samples.MultipleDbContexts
这有个多上下文的示例，你可以看看

**Comment by xuejmnet** [comment]
@gmf520 那么默认的defaultdbcontext是一定要有的吗还是说可以替换，我是想替换掉因为需要让dbcontext继承某个接口，default是你封装的我没办法方法继承某个接口

**Comment by xuejmnet** [comment]
@gmf520 如果无法替换是不是自定义的也需要继承dbcontextbase？

**Comment by gmf520** [comment]
@xuejmnet 自定义上下文类是要从DbContextBase派生的，框架中很多时候使用上下文都是转化为DbContextBase来使用。

**Comment by xuejmnet** [comment]
@gmf520 好的谢谢那么默认的defaultsbcontext是否是必须要有的

**Comment by gmf520** [comment]
非必须的，可以被替换掉
1. 实体要映射到新的数据上下文，通过如下方式的DbContextType属性：
```
    public class SqlServerEntityConfiguration : EntityTypeConfigurationBase<SqlServerEntity, Guid>
    {
        public override Type DbContextType { get; } = typeof(SqlServerDbContext);

        public override void Configure(EntityTypeBuilder<SqlServerEntity> builder)
        {  }
    }
```
2. 有几个内置的实体类，例如Function，EntityInfo等，也需要重新添加相应的EntityConfiguration配置类来映射新的数据上下文
3. 主程序中的Startups文件夹中的与数据上下文相关的类型也要重新定义

**Comment by xuejmnet** [comment]
好的谢谢
