### ISSUE TITLE
将实体主键改为雪花算法

### ISSUE THREAD

**Issue by gmf520** [i66soft/osharp#287]
## 您的功能请求与现有问题有关吗？请描述
- 实体主键的数据类型，int自增不容易应对数据迁移，合并，分布式，分库分表等需求，Guid太长且复杂
- long类型的雪花算法较短且有序，是最佳解决方案

## 描述您想要的需求方案
将实体主键类型更改为long类型，使用雪花算法给值，应用库：https://github.com/yitter/IdGenerator

**Comment by gmf520** [comment]
已在分支 [/dev/snow](https://github.com/dotnetcore/osharp/tree/dev/snow) 提供实现

**Comment by waleswood** [comment]
建议将雪花id的workerId暴露出来可以配置，目前是写死的
`services.TryAddSingleton<IKeyGenerator<long>>(new SnowKeyGenerator(new DefaultIdGenerator(new IdGeneratorOptions(1))));
        `

**Comment by gmf520** [comment]
@waleswood 这个用的是TryAddSingleton，只要你在这个之前注册一个`IKeyGenerator<long>`，这行就不起作用了

**Comment by waleswood** [comment]
是的，我也可以移除再添加。不过我觉得这样不够优雅

**Comment by lianglj** [comment]
您好，邮件已收到
